ktor:
  application:
    modules:
      - com.shandy.ApplicationKt.module
  deployment:
    port: 8081
postgres:
  url: "jdbc:postgresql://192.168.16.1:5432/postgres"
  user: test
  password: 'sikbbang2@'